# Copyright (c) 2011 Sung Pae <self@sungpae.com>
# Distributed under the MIT license.
# http://www.opensource.org/licenses/mit-license.php

task :default => :update

def add_ipv6 hostbuf
  invalid = Regexp.quote '0.0.0.0'
  local = Regexp.quote '127.0.0.1'
  hostbuf.gsub /^(?:#{invalid}|#{local})\s+(.*)$/, "0.0.0.0 \\1\n::      \\1"
end

desc 'Update adblock domains in hosts'
task :update do
  require 'net/http'

  lines = File.readlines 'hosts'
  url = 'http://winhelp2002.mvps.org/hosts.txt'

  if index = lines.index { |l| l =~ /\A### ADBLOCK/ }
    puts "Updating adblock domains from #{url}"

    hosts = lines[0..index].join
    adhosts = Net::HTTP.get(URI.parse url).gsub /\r\n/, "\n"

    File.open 'hosts', 'w' do |f|
      f.puts hosts, add_ipv6(adhosts)
    end
  end
end
