# Copyright (c) 2011 Sung Pae <self@sungpae.com>
# Distributed under the MIT license.
# http://www.opensource.org/licenses/mit-license.php

task :default => :localhosts6

desc 'Create IPv6 entries for all 127.0.0.1 entries in the hosts file'
task :localhosts6 do
  hosts = File.read 'hosts'
  ipv6hosts = Hash[hosts.split("\n").grep(/\A\s*::1\s+(.*)/) { [$1, 1] }]

  buf = hosts.lines.map do |line|
    match = line.match /\A\s*127\.0\.0\.1\s+(.*)/
    next line if match.nil? or ipv6hosts.has_key? match[1]
    line + line.sub(/\A(\s*)127\.0\.0\.1/, '\1::1      ')
  end.join

  File.open('hosts', 'w') { |f| f.write buf }
end

desc 'Update adblock domains in hosts'
task :update do
  require 'net/http'

  lines = File.readlines 'hosts'
  url = 'http://winhelp2002.mvps.org/hosts.txt'

  if index = lines.index { |l| l =~ /\A### ADBLOCK/ }
    puts "Updating adblock domains from #{url}"

    hosts = lines[0..index].join
    adhosts = Net::HTTP.get(URI.parse url).gsub /\r\n/, "\n"

    File.open 'hosts', 'w' do |f|
      f.puts hosts, adhosts
    end

    Rake::Task[:localhosts6].invoke
  end
end
